### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by SamVerschueren** [kevva/kap-clipboard#4]
I want to write tests for this plugin but am probably too inexperienced with Electron. The thing is that the plugin requires `electron`. So I installed electron as dev dependency but apparently that doesn't work. Is it possible to even do test this?

// @sindresorhus @kevva

**Comment by sindresorhus** [comment]
There's https://github.com/electron/spectron, but it's more for testing apps. You could also mock the Electron method. What are you trying to do?

**Comment by SamVerschueren** [comment]
I added tests in PR #5. I wanted to capture the call to `clipboard.writeBuffer` which is an Electron call. I mocked Electron with `proxyquire` which works well. If you think it should be done differently, let me know.
